# Generated by Django 5.0.4 on 2024-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_country_book_published_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='address',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_countries',
        ),
        migrations.AlterField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
